### PR TITLE
updated css

### PR DESCRIPTION
**Pull request by prateekraiger**
In This Repo I had made a good layout with some fresh colors that makes up the github repo even more good and give it a perfect card like structure

### CODE REVIEW

**Review by BamaCharanChhandogi — CHANGES_REQUESTED** [review]
Thanks for improving the design. But there is an error showing. Could you fix this issue? If you are not able to fix the issue, you can keep the previous `js` file. 

image

**Comment by prateekraiger** [comment]
done as you said check now

**Comment by BamaCharanChhandogi** [comment]
> done as you said check now

As I see, you did not change anything.

**Comment by prateekraiger** [comment]
now check for it

**Comment by prateekraiger** [comment]
if no error accept the changes

**Review by BamaCharanChhandogi — COMMENTED** [review]
I am seeing my storybook code also not working, I do not know what's happening actually. I would merge if I solved the issue.

**Pull request closed without merging**
